// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shoe.Models;

public partial class Manufacturer
{
    public uint ManufacturerId { get; set; }

    public string ManufacturerName { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}