// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shoe.Models;

public partial class OrderItem
{
    public uint OrderId { get; set; }

    public uint ProductId { get; set; }

    public uint Quantity { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}