// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shoe.Models;

public partial class Order
{
    public uint OrderId { get; set; }

    public DateOnly? OrderDate { get; set; }

    public DateOnly DeliveryDate { get; set; }

    public uint PickupPointId { get; set; }

    public uint CustomerId { get; set; }

    public uint PickupCode { get; set; }

    public byte StatusId { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual PickupPoint PickupPoint { get; set; }

    public virtual OrderStatus Status { get; set; }
}