// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shoe.Models;

public partial class Product
{
    public uint ProductId { get; set; }

    public string Article { get; set; }

    public string ProductName { get; set; }

    public string Unit { get; set; }

    public decimal Price { get; set; }

    public uint SupplierId { get; set; }

    public uint ManufacturerId { get; set; }

    public uint CategoryId { get; set; }

    public decimal DiscountPercent { get; set; }

    public uint StockQuantity { get; set; }

    public string Description { get; set; }

    public string Photo { get; set; }

    public virtual Category Category { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Supplier Supplier { get; set; }
}