// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shoe.Models;

public partial class User
{
    public uint UserId { get; set; }

    public uint RoleId { get; set; }

    public string FullName { get; set; }

    public string Login { get; set; }

    public string PasswordHash { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Role Role { get; set; }
}